SEME-1983-BE-Rubocop-petal-with-all-rubocop-config-for-new-projects
petalmd/rubocop-petal pull request #41
Opened 2023-05-08 18:07 UTC by nelalampetal

## What's the PR about

[SEME-1983-BE-Rubocop-petal-with-all-rubocop-config-for-new-projects](https://petalmd.atlassian.net/browse/SEME-1983)

## Work done

Unified cops used by monolith to be reused by seme-microservice and new projects.

## How to test
-The new project should use this gem petal-rubocop and inherit the base configuration as show below:

`require:
- rubocop-rails
- rubocop-performance
- rubocop-rspec
- rubocop-petal
inherit_mode:
  merge:
  - Exclude
inherit_gem:
  rubocop-petal: config/default.yml

Rails/ModelAccessFromApiController:
  Enabled: false`

2023-05-09 13:03 UTC, Bhacaz requested changes

2023-05-09 13:03 UTC, Bhacaz commented on lib/rubocop/petal/version.rb
> +    VERSION = '1.0.0'
I'll will handle the version once merge. just add an entry in the changelog under `master` and remove change relative to bumping the gem version.

2023-05-09 13:05 UTC, Bhacaz requested changes
You should add as dependency 

* rubocop-performance
* rubocop-rspec

in the gemspec, so the cop will come when simply using `rubocop-petal`

2023-05-09 13:14 UTC, Bhacaz requested changes

2023-05-09 13:14 UTC, Bhacaz commented on lib/rubocop/petal/inject.rb
> +        Rails.logger.info "configuration from #{path}" if ConfigLoader.debug?
We are not in a Rails context here. I think `puts` is the good way, Plus, this is auto generated file by rubocop generator.

2023-05-09 20:41 UTC, nelalampetal commented on lib/rubocop/petal/version.rb
> +    VERSION = '1.0.0'
okay

2023-05-11 18:49 UTC, Bhacaz commented
An example I followed: https://github.com/github/rubocop-github#usage

I updated the readme to show how import the config in an other project.

2023-05-12 17:48 UTC, Bhacaz approved these changes

2023-05-12 17:48 UTC, merged

2023-05-12 19:24 UTC, IMillerPetal commented on config/base.yml
> +  Max: 20
@Bhacaz  Did you revisit all the cops rules?
This gem is meant to be a standard for all projects, monolith can override some of them to handle tech debt, right?

2023-05-12 19:25 UTC, Bhacaz commented on config/base.yml
> +  Max: 20
Yes I check it all. Monolith have 40. 20 seams a good compromise

2023-05-12 19:26 UTC, IMillerPetal commented on config/base.yml
> +  Max: 20
Great. Thanks!

2023-05-15 18:54 UTC, nelalampetal commented
@Bhacaz I've tried to include this new version 0.9.0 in our project, but I think we are missing any process to keep this 
 `/config/base.yml` file when bundle the gem. 
Please see the output dir list just after install the gem

```
Installing rubocop-petal 0.9.0
Bundle complete! 18 Gemfile dependencies, 103 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
nelalam@petal-0232 secure-messaging % ls -lrt /Users/nelalam/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rubocop-petal-0.9.0/config/*
-rw-r--r--@ 1 nelalam  staff  2412 May 15 14:48 /Users/nelalam/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rubocop-petal-0.9.0/config/default.yml
```
The result is 

```
nelalam@petal-0232 secure-messaging % rubocop 
Configuration file not found: /Users/nelalam/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rubocop-petal-0.9.0/config/base.yml
```