new cop for enum starting value
petalmd/rubocop-petal pull request #57
Opened 2023-06-19 19:21 UTC by faridanoosheh

It is in response to this issue: https://github.com/petalmd/rubocop-petal/issues/56

2023-06-20 12:05 UTC, Bhacaz reviewed
The entry in the changelog should be under `# main`

2023-06-20 13:43 UTC, Bhacaz commented on CHANGELOG.md
> +* Added cop `Rails/EnumStartingValue` ([#57](https://github.com/petalmd/rubocop-petal/pull/57))
Under `# main`, the version title will be created when ready to release

2023-06-20 13:54 UTC, faridanoosheh commented on CHANGELOG.md
> +* Added cop `Rails/EnumStartingValue` ([#57](https://github.com/petalmd/rubocop-petal/pull/57))
Aha,
That is what I doubt about

2023-06-21 12:16 UTC, Bhacaz requested changes
I had some error when trying it our project. Something, the enum value is a constant, [example](https://github.com/petalmd/petalmd.rails/blob/1d5f0d1c4d839b51ca66bc42d64c4b8e2e5df169/app/models/schedule/task_kind_attribute.rb#L7-L7)

```
undefined method `value' for s(:const, nil, :SomeConstant):RuboCop::AST::ConstNode
/Users/jfbastien/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/rubocop-petal-f6edf46de432/lib/rubocop/cop/rails/enum_starting_value.rb:35:in `block in start_with_zero?'
/Users/jfbastien/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/rubocop-petal-f6edf46de432/lib/rubocop/cop/rails/enum_starting_value.rb:34:in `any?'
/Users/jfbastien/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/rubocop-petal-f6edf46de432/lib/rubocop/cop/rails/enum_starting_value.rb:34:in `start_with_zero?'
/Users/jfbastien/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/rubocop-petal-f6edf46de432/lib/rubocop/cop/rails/enum_starting_value.rb:30:in `on_send'
```

2023-06-21 14:15 UTC, Bhacaz commented on spec/rubocop/cop/rails/enum_starting_value_spec.rb
> +            enum my_enum: {state1: 0, state2: 2}
It may sound weird, but can you add a specs to that check that no value should be 0.

Like

```ruby
enum my_enum: {state1: 1, state2: 0}
```

2023-06-22 13:24 UTC, Bhacaz approved these changes
Awesome, thanks

2023-06-22 13:25 UTC, merged