MEDO/RTO-2676 - Add new custom cop to prevent early nil returns in booking hub workers
petalmd/rubocop-petal pull request #58
Opened 2023-08-18 17:28 UTC by LittleCatBear

Part of https://petalmd.atlassian.net/browse/RTO-2676: 
Add a new custom cop to prevent adding more new workers with nil returns while we're working on a solution to log data for existing cases.

This does not take into account cases where exceptions are being rescued and not re raises

2023-08-21 19:11 UTC, LittleCatBear commented
cc @ericproulx, si tu as un moment pour y jeter un oeil stp :) 
une question qu'il me reste aussi, si cette PR est merge, comment on fait pour commencer a "sync" avec petalrails? est-ce que le build sur petalrails master va commencer a fail si on reference le nouveau cop avec les fichiers a exclure dans rubocop-todo, mais la nouvelle version de rubocop-petal a pas ete encore release?

2023-08-28 08:54 UTC, mehdi-farsi requested changes
Almost LGTM.

Juste une petite question sur laquelle il faudrait statuer. 🙏

2023-08-28 08:54 UTC, mehdi-farsi commented on lib/rubocop/cop/sidekiq/no_nil_return.rb
> +          add_offense(node) if node.arguments.first&.nil_type? || node.arguments.empty?
Bien joué!

J'ai juste une question générale: Est-ce qu'on voudrait pas catch tous les `return`s, même ceux qui ne renvoient pas `nil`?

Genre

```ruby
return
return false
return nil
return true
return object
# etc..
```

2023-08-28 09:07 UTC, mehdi-farsi commented on lib/rubocop/cop/sidekiq/no_nil_return.rb
> +          add_offense(node) if node.arguments.first&.nil_type? || node.arguments.empty?
Vu avec @aymericdo. On se sert malheureusement de la valeur de retour de certains workers en synchrone.

Du coup, c'est très bien que ce cop ne se concentre que sur les valeurs `nil` pour éviter de casser la logique existante.

2023-08-28 09:08 UTC, mehdi-farsi approved these changes
LGTM

2023-08-28 15:42 UTC, aymericdo approved these changes

2023-08-30 08:01 UTC, aymericdo commented
@ericproulx C'est bon pour toi ? Je merge ?

2023-08-30 08:29 UTC, ericproulx approved these changes

2023-08-30 08:46 UTC, merged